export const conversationStarters = [
  "Your favorite book or movie",
  "Travel experiences",
  "The future of technology",
  "Environmental conservation efforts",
  "Famous historical figures",
  "Social media impact on society",
  "Personal hobbies or interests",
  "Cultural traditions",
  "Global warming and climate change",
  "Space exploration",
  "Music preferences",
  "Education system reforms",
  "Wildlife conservation",
  "Health and wellness trends",
  "Famous landmarks around the world",
  "Innovative inventions",
  "The importance of teamwork",
  "Current events and news topics",
  "Diversity and inclusion",
  "Philosophical discussions",
  "Entrepreneurship and startups",
  "World cuisine and food culture",
  "Sustainable living practices",
  "Art and creativity",
  "Time management strategies",
  "Career aspirations",
  "Human rights issues",
  "Fitness and exercise routines",
  "Leadership qualities",
  "Cultural celebrations and festivals",
  "Mental health awareness",
  "Economic development initiatives",
  "Self-improvement techniques",
  "Fashion trends and style preferences",
  "Personal finance management",
  "Innovation in healthcare",
  "Stress management techniques",
  "Gender equality discussions",
  "DIY projects and crafts",
  "Endangered species conservation",
  "Artificial intelligence and automation",
  "Mindfulness practices",
  "Renewable energy solutions",
  "Ethical dilemmas",
  "Science fiction vs. reality",
  "Cultural stereotypes and misconceptions",
  "Innovations in transportation",
  "Social justice movements",
  "Virtual reality experiences",
  "The impact of social media on mental health",
];
